version: '3'
services:
  postgres:
    image: postgres:10
    container_name: postgres_test
    environment:
      POSTGRES_DB: guillotina
      POSTGRES_USER: guillotina
      POSTGRES_PASSWORD: guillotina
  guillotina:
    image: plone/guillotina_cms:latest
    command: sh -c "sleep 5 && g -c /usr/src/app/config.yml"
    ports:
      - '8081:8081'
    links:
      - postgres
    volumes:
      - ${PWD}/g-api/config.yaml:/usr/src/app/config.yml
